version: '3.8'

services:

  db:
    image: mysql:8.0.28
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: web
      MYSQL_USER: alvaro
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: alvaro
    ports:
      - 3306:3306
    volumes:
    - ./sql/db.sql:/docker-entrypoint-initdb.d/1.sql
    - ./sql/sample.sql:/docker-entrypoint-initdb.d/2.sql